const quotes = [
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
    "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "I have not failed. I’ve just found 10,000 ways that won’t work. – Thomas Edison",
    "Be the change that you wish to see in the world. – Mahatma Gandhi",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. – Sheryl Sandberg",
    "Dream big and dare to fail. – Norman Vaughan",
    "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
    "The man who has confidence in himself gains the confidence of others. – Hasidic Proverb",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Fall seven times and stand up eight. – Japanese Proverb",
    "Everything you’ve ever wanted is on the other side of fear. – George Addair",
    "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
    "It is never too late to be what you might have been. – George Eliot",
    "Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "I never dreamed about success, I worked for it. – Estée Lauder",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. – Joshua J. Marine",
    "Success is how high you bounce when you hit bottom. – George S. Patton",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "The best revenge is massive success. – Frank Sinatra",
    "Opportunities don't happen. You create them. – Chris Grosser",
    "I failed my way to success. – Thomas Edison",
    "Strive not to be a success, but rather to be of value. – Albert Einstein"
    // Add additional quotes here if needed...
  ];
  